// Computer_System_mm_interconnect_0.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 15.0 145

`timescale 1 ps / 1 ps
module Computer_System_mm_interconnect_0 (
		input  wire        System_PLL_sys_clk_clk,                            //                          System_PLL_sys_clk.clk
		input  wire        External_master_reset_reset_bridge_in_reset_reset, // External_master_reset_reset_bridge_in_reset.reset
		input  wire [29:0] External_master_avalon_master_address,             //               External_master_avalon_master.address
		output wire        External_master_avalon_master_waitrequest,         //                                            .waitrequest
		input  wire [3:0]  External_master_avalon_master_byteenable,          //                                            .byteenable
		input  wire        External_master_avalon_master_read,                //                                            .read
		output wire [31:0] External_master_avalon_master_readdata,            //                                            .readdata
		input  wire        External_master_avalon_master_write,               //                                            .write
		input  wire [31:0] External_master_avalon_master_writedata,           //                                            .writedata
		output wire [1:0]  HEX3_HEX0_s1_address,                              //                                HEX3_HEX0_s1.address
		output wire        HEX3_HEX0_s1_write,                                //                                            .write
		input  wire [31:0] HEX3_HEX0_s1_readdata,                             //                                            .readdata
		output wire [31:0] HEX3_HEX0_s1_writedata,                            //                                            .writedata
		output wire        HEX3_HEX0_s1_chipselect,                           //                                            .chipselect
		output wire [1:0]  LEDs_s1_address,                                   //                                     LEDs_s1.address
		output wire        LEDs_s1_write,                                     //                                            .write
		input  wire [31:0] LEDs_s1_readdata,                                  //                                            .readdata
		output wire [31:0] LEDs_s1_writedata,                                 //                                            .writedata
		output wire        LEDs_s1_chipselect                                 //                                            .chipselect
	);

	wire          external_master_avalon_master_translator_avalon_universal_master_0_waitrequest;   // External_master_avalon_master_agent:av_waitrequest -> External_master_avalon_master_translator:uav_waitrequest
	wire   [31:0] external_master_avalon_master_translator_avalon_universal_master_0_readdata;      // External_master_avalon_master_agent:av_readdata -> External_master_avalon_master_translator:uav_readdata
	wire          external_master_avalon_master_translator_avalon_universal_master_0_debugaccess;   // External_master_avalon_master_translator:uav_debugaccess -> External_master_avalon_master_agent:av_debugaccess
	wire   [29:0] external_master_avalon_master_translator_avalon_universal_master_0_address;       // External_master_avalon_master_translator:uav_address -> External_master_avalon_master_agent:av_address
	wire          external_master_avalon_master_translator_avalon_universal_master_0_read;          // External_master_avalon_master_translator:uav_read -> External_master_avalon_master_agent:av_read
	wire    [3:0] external_master_avalon_master_translator_avalon_universal_master_0_byteenable;    // External_master_avalon_master_translator:uav_byteenable -> External_master_avalon_master_agent:av_byteenable
	wire          external_master_avalon_master_translator_avalon_universal_master_0_readdatavalid; // External_master_avalon_master_agent:av_readdatavalid -> External_master_avalon_master_translator:uav_readdatavalid
	wire          external_master_avalon_master_translator_avalon_universal_master_0_lock;          // External_master_avalon_master_translator:uav_lock -> External_master_avalon_master_agent:av_lock
	wire          external_master_avalon_master_translator_avalon_universal_master_0_write;         // External_master_avalon_master_translator:uav_write -> External_master_avalon_master_agent:av_write
	wire   [31:0] external_master_avalon_master_translator_avalon_universal_master_0_writedata;     // External_master_avalon_master_translator:uav_writedata -> External_master_avalon_master_agent:av_writedata
	wire    [2:0] external_master_avalon_master_translator_avalon_universal_master_0_burstcount;    // External_master_avalon_master_translator:uav_burstcount -> External_master_avalon_master_agent:av_burstcount
	wire          rsp_mux_src_valid;                                                                // rsp_mux:src_valid -> External_master_avalon_master_agent:rp_valid
	wire   [99:0] rsp_mux_src_data;                                                                 // rsp_mux:src_data -> External_master_avalon_master_agent:rp_data
	wire          rsp_mux_src_ready;                                                                // External_master_avalon_master_agent:rp_ready -> rsp_mux:src_ready
	wire    [1:0] rsp_mux_src_channel;                                                              // rsp_mux:src_channel -> External_master_avalon_master_agent:rp_channel
	wire          rsp_mux_src_startofpacket;                                                        // rsp_mux:src_startofpacket -> External_master_avalon_master_agent:rp_startofpacket
	wire          rsp_mux_src_endofpacket;                                                          // rsp_mux:src_endofpacket -> External_master_avalon_master_agent:rp_endofpacket
	wire   [31:0] leds_s1_agent_m0_readdata;                                                        // LEDs_s1_translator:uav_readdata -> LEDs_s1_agent:m0_readdata
	wire          leds_s1_agent_m0_waitrequest;                                                     // LEDs_s1_translator:uav_waitrequest -> LEDs_s1_agent:m0_waitrequest
	wire          leds_s1_agent_m0_debugaccess;                                                     // LEDs_s1_agent:m0_debugaccess -> LEDs_s1_translator:uav_debugaccess
	wire   [29:0] leds_s1_agent_m0_address;                                                         // LEDs_s1_agent:m0_address -> LEDs_s1_translator:uav_address
	wire    [3:0] leds_s1_agent_m0_byteenable;                                                      // LEDs_s1_agent:m0_byteenable -> LEDs_s1_translator:uav_byteenable
	wire          leds_s1_agent_m0_read;                                                            // LEDs_s1_agent:m0_read -> LEDs_s1_translator:uav_read
	wire          leds_s1_agent_m0_readdatavalid;                                                   // LEDs_s1_translator:uav_readdatavalid -> LEDs_s1_agent:m0_readdatavalid
	wire          leds_s1_agent_m0_lock;                                                            // LEDs_s1_agent:m0_lock -> LEDs_s1_translator:uav_lock
	wire   [31:0] leds_s1_agent_m0_writedata;                                                       // LEDs_s1_agent:m0_writedata -> LEDs_s1_translator:uav_writedata
	wire          leds_s1_agent_m0_write;                                                           // LEDs_s1_agent:m0_write -> LEDs_s1_translator:uav_write
	wire    [2:0] leds_s1_agent_m0_burstcount;                                                      // LEDs_s1_agent:m0_burstcount -> LEDs_s1_translator:uav_burstcount
	wire          leds_s1_agent_rf_source_valid;                                                    // LEDs_s1_agent:rf_source_valid -> LEDs_s1_agent_rsp_fifo:in_valid
	wire  [100:0] leds_s1_agent_rf_source_data;                                                     // LEDs_s1_agent:rf_source_data -> LEDs_s1_agent_rsp_fifo:in_data
	wire          leds_s1_agent_rf_source_ready;                                                    // LEDs_s1_agent_rsp_fifo:in_ready -> LEDs_s1_agent:rf_source_ready
	wire          leds_s1_agent_rf_source_startofpacket;                                            // LEDs_s1_agent:rf_source_startofpacket -> LEDs_s1_agent_rsp_fifo:in_startofpacket
	wire          leds_s1_agent_rf_source_endofpacket;                                              // LEDs_s1_agent:rf_source_endofpacket -> LEDs_s1_agent_rsp_fifo:in_endofpacket
	wire          leds_s1_agent_rsp_fifo_out_valid;                                                 // LEDs_s1_agent_rsp_fifo:out_valid -> LEDs_s1_agent:rf_sink_valid
	wire  [100:0] leds_s1_agent_rsp_fifo_out_data;                                                  // LEDs_s1_agent_rsp_fifo:out_data -> LEDs_s1_agent:rf_sink_data
	wire          leds_s1_agent_rsp_fifo_out_ready;                                                 // LEDs_s1_agent:rf_sink_ready -> LEDs_s1_agent_rsp_fifo:out_ready
	wire          leds_s1_agent_rsp_fifo_out_startofpacket;                                         // LEDs_s1_agent_rsp_fifo:out_startofpacket -> LEDs_s1_agent:rf_sink_startofpacket
	wire          leds_s1_agent_rsp_fifo_out_endofpacket;                                           // LEDs_s1_agent_rsp_fifo:out_endofpacket -> LEDs_s1_agent:rf_sink_endofpacket
	wire          cmd_mux_src_valid;                                                                // cmd_mux:src_valid -> LEDs_s1_agent:cp_valid
	wire   [99:0] cmd_mux_src_data;                                                                 // cmd_mux:src_data -> LEDs_s1_agent:cp_data
	wire          cmd_mux_src_ready;                                                                // LEDs_s1_agent:cp_ready -> cmd_mux:src_ready
	wire    [1:0] cmd_mux_src_channel;                                                              // cmd_mux:src_channel -> LEDs_s1_agent:cp_channel
	wire          cmd_mux_src_startofpacket;                                                        // cmd_mux:src_startofpacket -> LEDs_s1_agent:cp_startofpacket
	wire          cmd_mux_src_endofpacket;                                                          // cmd_mux:src_endofpacket -> LEDs_s1_agent:cp_endofpacket
	wire   [31:0] hex3_hex0_s1_agent_m0_readdata;                                                   // HEX3_HEX0_s1_translator:uav_readdata -> HEX3_HEX0_s1_agent:m0_readdata
	wire          hex3_hex0_s1_agent_m0_waitrequest;                                                // HEX3_HEX0_s1_translator:uav_waitrequest -> HEX3_HEX0_s1_agent:m0_waitrequest
	wire          hex3_hex0_s1_agent_m0_debugaccess;                                                // HEX3_HEX0_s1_agent:m0_debugaccess -> HEX3_HEX0_s1_translator:uav_debugaccess
	wire   [29:0] hex3_hex0_s1_agent_m0_address;                                                    // HEX3_HEX0_s1_agent:m0_address -> HEX3_HEX0_s1_translator:uav_address
	wire    [3:0] hex3_hex0_s1_agent_m0_byteenable;                                                 // HEX3_HEX0_s1_agent:m0_byteenable -> HEX3_HEX0_s1_translator:uav_byteenable
	wire          hex3_hex0_s1_agent_m0_read;                                                       // HEX3_HEX0_s1_agent:m0_read -> HEX3_HEX0_s1_translator:uav_read
	wire          hex3_hex0_s1_agent_m0_readdatavalid;                                              // HEX3_HEX0_s1_translator:uav_readdatavalid -> HEX3_HEX0_s1_agent:m0_readdatavalid
	wire          hex3_hex0_s1_agent_m0_lock;                                                       // HEX3_HEX0_s1_agent:m0_lock -> HEX3_HEX0_s1_translator:uav_lock
	wire   [31:0] hex3_hex0_s1_agent_m0_writedata;                                                  // HEX3_HEX0_s1_agent:m0_writedata -> HEX3_HEX0_s1_translator:uav_writedata
	wire          hex3_hex0_s1_agent_m0_write;                                                      // HEX3_HEX0_s1_agent:m0_write -> HEX3_HEX0_s1_translator:uav_write
	wire    [2:0] hex3_hex0_s1_agent_m0_burstcount;                                                 // HEX3_HEX0_s1_agent:m0_burstcount -> HEX3_HEX0_s1_translator:uav_burstcount
	wire          hex3_hex0_s1_agent_rf_source_valid;                                               // HEX3_HEX0_s1_agent:rf_source_valid -> HEX3_HEX0_s1_agent_rsp_fifo:in_valid
	wire  [100:0] hex3_hex0_s1_agent_rf_source_data;                                                // HEX3_HEX0_s1_agent:rf_source_data -> HEX3_HEX0_s1_agent_rsp_fifo:in_data
	wire          hex3_hex0_s1_agent_rf_source_ready;                                               // HEX3_HEX0_s1_agent_rsp_fifo:in_ready -> HEX3_HEX0_s1_agent:rf_source_ready
	wire          hex3_hex0_s1_agent_rf_source_startofpacket;                                       // HEX3_HEX0_s1_agent:rf_source_startofpacket -> HEX3_HEX0_s1_agent_rsp_fifo:in_startofpacket
	wire          hex3_hex0_s1_agent_rf_source_endofpacket;                                         // HEX3_HEX0_s1_agent:rf_source_endofpacket -> HEX3_HEX0_s1_agent_rsp_fifo:in_endofpacket
	wire          hex3_hex0_s1_agent_rsp_fifo_out_valid;                                            // HEX3_HEX0_s1_agent_rsp_fifo:out_valid -> HEX3_HEX0_s1_agent:rf_sink_valid
	wire  [100:0] hex3_hex0_s1_agent_rsp_fifo_out_data;                                             // HEX3_HEX0_s1_agent_rsp_fifo:out_data -> HEX3_HEX0_s1_agent:rf_sink_data
	wire          hex3_hex0_s1_agent_rsp_fifo_out_ready;                                            // HEX3_HEX0_s1_agent:rf_sink_ready -> HEX3_HEX0_s1_agent_rsp_fifo:out_ready
	wire          hex3_hex0_s1_agent_rsp_fifo_out_startofpacket;                                    // HEX3_HEX0_s1_agent_rsp_fifo:out_startofpacket -> HEX3_HEX0_s1_agent:rf_sink_startofpacket
	wire          hex3_hex0_s1_agent_rsp_fifo_out_endofpacket;                                      // HEX3_HEX0_s1_agent_rsp_fifo:out_endofpacket -> HEX3_HEX0_s1_agent:rf_sink_endofpacket
	wire          cmd_mux_001_src_valid;                                                            // cmd_mux_001:src_valid -> HEX3_HEX0_s1_agent:cp_valid
	wire   [99:0] cmd_mux_001_src_data;                                                             // cmd_mux_001:src_data -> HEX3_HEX0_s1_agent:cp_data
	wire          cmd_mux_001_src_ready;                                                            // HEX3_HEX0_s1_agent:cp_ready -> cmd_mux_001:src_ready
	wire    [1:0] cmd_mux_001_src_channel;                                                          // cmd_mux_001:src_channel -> HEX3_HEX0_s1_agent:cp_channel
	wire          cmd_mux_001_src_startofpacket;                                                    // cmd_mux_001:src_startofpacket -> HEX3_HEX0_s1_agent:cp_startofpacket
	wire          cmd_mux_001_src_endofpacket;                                                      // cmd_mux_001:src_endofpacket -> HEX3_HEX0_s1_agent:cp_endofpacket
	wire          external_master_avalon_master_agent_cp_valid;                                     // External_master_avalon_master_agent:cp_valid -> router:sink_valid
	wire   [99:0] external_master_avalon_master_agent_cp_data;                                      // External_master_avalon_master_agent:cp_data -> router:sink_data
	wire          external_master_avalon_master_agent_cp_ready;                                     // router:sink_ready -> External_master_avalon_master_agent:cp_ready
	wire          external_master_avalon_master_agent_cp_startofpacket;                             // External_master_avalon_master_agent:cp_startofpacket -> router:sink_startofpacket
	wire          external_master_avalon_master_agent_cp_endofpacket;                               // External_master_avalon_master_agent:cp_endofpacket -> router:sink_endofpacket
	wire          router_src_valid;                                                                 // router:src_valid -> cmd_demux:sink_valid
	wire   [99:0] router_src_data;                                                                  // router:src_data -> cmd_demux:sink_data
	wire          router_src_ready;                                                                 // cmd_demux:sink_ready -> router:src_ready
	wire    [1:0] router_src_channel;                                                               // router:src_channel -> cmd_demux:sink_channel
	wire          router_src_startofpacket;                                                         // router:src_startofpacket -> cmd_demux:sink_startofpacket
	wire          router_src_endofpacket;                                                           // router:src_endofpacket -> cmd_demux:sink_endofpacket
	wire          leds_s1_agent_rp_valid;                                                           // LEDs_s1_agent:rp_valid -> router_001:sink_valid
	wire   [99:0] leds_s1_agent_rp_data;                                                            // LEDs_s1_agent:rp_data -> router_001:sink_data
	wire          leds_s1_agent_rp_ready;                                                           // router_001:sink_ready -> LEDs_s1_agent:rp_ready
	wire          leds_s1_agent_rp_startofpacket;                                                   // LEDs_s1_agent:rp_startofpacket -> router_001:sink_startofpacket
	wire          leds_s1_agent_rp_endofpacket;                                                     // LEDs_s1_agent:rp_endofpacket -> router_001:sink_endofpacket
	wire          router_001_src_valid;                                                             // router_001:src_valid -> rsp_demux:sink_valid
	wire   [99:0] router_001_src_data;                                                              // router_001:src_data -> rsp_demux:sink_data
	wire          router_001_src_ready;                                                             // rsp_demux:sink_ready -> router_001:src_ready
	wire    [1:0] router_001_src_channel;                                                           // router_001:src_channel -> rsp_demux:sink_channel
	wire          router_001_src_startofpacket;                                                     // router_001:src_startofpacket -> rsp_demux:sink_startofpacket
	wire          router_001_src_endofpacket;                                                       // router_001:src_endofpacket -> rsp_demux:sink_endofpacket
	wire          hex3_hex0_s1_agent_rp_valid;                                                      // HEX3_HEX0_s1_agent:rp_valid -> router_002:sink_valid
	wire   [99:0] hex3_hex0_s1_agent_rp_data;                                                       // HEX3_HEX0_s1_agent:rp_data -> router_002:sink_data
	wire          hex3_hex0_s1_agent_rp_ready;                                                      // router_002:sink_ready -> HEX3_HEX0_s1_agent:rp_ready
	wire          hex3_hex0_s1_agent_rp_startofpacket;                                              // HEX3_HEX0_s1_agent:rp_startofpacket -> router_002:sink_startofpacket
	wire          hex3_hex0_s1_agent_rp_endofpacket;                                                // HEX3_HEX0_s1_agent:rp_endofpacket -> router_002:sink_endofpacket
	wire          router_002_src_valid;                                                             // router_002:src_valid -> rsp_demux_001:sink_valid
	wire   [99:0] router_002_src_data;                                                              // router_002:src_data -> rsp_demux_001:sink_data
	wire          router_002_src_ready;                                                             // rsp_demux_001:sink_ready -> router_002:src_ready
	wire    [1:0] router_002_src_channel;                                                           // router_002:src_channel -> rsp_demux_001:sink_channel
	wire          router_002_src_startofpacket;                                                     // router_002:src_startofpacket -> rsp_demux_001:sink_startofpacket
	wire          router_002_src_endofpacket;                                                       // router_002:src_endofpacket -> rsp_demux_001:sink_endofpacket
	wire          cmd_demux_src0_valid;                                                             // cmd_demux:src0_valid -> cmd_mux:sink0_valid
	wire   [99:0] cmd_demux_src0_data;                                                              // cmd_demux:src0_data -> cmd_mux:sink0_data
	wire          cmd_demux_src0_ready;                                                             // cmd_mux:sink0_ready -> cmd_demux:src0_ready
	wire    [1:0] cmd_demux_src0_channel;                                                           // cmd_demux:src0_channel -> cmd_mux:sink0_channel
	wire          cmd_demux_src0_startofpacket;                                                     // cmd_demux:src0_startofpacket -> cmd_mux:sink0_startofpacket
	wire          cmd_demux_src0_endofpacket;                                                       // cmd_demux:src0_endofpacket -> cmd_mux:sink0_endofpacket
	wire          cmd_demux_src1_valid;                                                             // cmd_demux:src1_valid -> cmd_mux_001:sink0_valid
	wire   [99:0] cmd_demux_src1_data;                                                              // cmd_demux:src1_data -> cmd_mux_001:sink0_data
	wire          cmd_demux_src1_ready;                                                             // cmd_mux_001:sink0_ready -> cmd_demux:src1_ready
	wire    [1:0] cmd_demux_src1_channel;                                                           // cmd_demux:src1_channel -> cmd_mux_001:sink0_channel
	wire          cmd_demux_src1_startofpacket;                                                     // cmd_demux:src1_startofpacket -> cmd_mux_001:sink0_startofpacket
	wire          cmd_demux_src1_endofpacket;                                                       // cmd_demux:src1_endofpacket -> cmd_mux_001:sink0_endofpacket
	wire          rsp_demux_src0_valid;                                                             // rsp_demux:src0_valid -> rsp_mux:sink0_valid
	wire   [99:0] rsp_demux_src0_data;                                                              // rsp_demux:src0_data -> rsp_mux:sink0_data
	wire          rsp_demux_src0_ready;                                                             // rsp_mux:sink0_ready -> rsp_demux:src0_ready
	wire    [1:0] rsp_demux_src0_channel;                                                           // rsp_demux:src0_channel -> rsp_mux:sink0_channel
	wire          rsp_demux_src0_startofpacket;                                                     // rsp_demux:src0_startofpacket -> rsp_mux:sink0_startofpacket
	wire          rsp_demux_src0_endofpacket;                                                       // rsp_demux:src0_endofpacket -> rsp_mux:sink0_endofpacket
	wire          rsp_demux_001_src0_valid;                                                         // rsp_demux_001:src0_valid -> rsp_mux:sink1_valid
	wire   [99:0] rsp_demux_001_src0_data;                                                          // rsp_demux_001:src0_data -> rsp_mux:sink1_data
	wire          rsp_demux_001_src0_ready;                                                         // rsp_mux:sink1_ready -> rsp_demux_001:src0_ready
	wire    [1:0] rsp_demux_001_src0_channel;                                                       // rsp_demux_001:src0_channel -> rsp_mux:sink1_channel
	wire          rsp_demux_001_src0_startofpacket;                                                 // rsp_demux_001:src0_startofpacket -> rsp_mux:sink1_startofpacket
	wire          rsp_demux_001_src0_endofpacket;                                                   // rsp_demux_001:src0_endofpacket -> rsp_mux:sink1_endofpacket
	wire          leds_s1_agent_rdata_fifo_src_valid;                                               // LEDs_s1_agent:rdata_fifo_src_valid -> avalon_st_adapter:in_0_valid
	wire   [33:0] leds_s1_agent_rdata_fifo_src_data;                                                // LEDs_s1_agent:rdata_fifo_src_data -> avalon_st_adapter:in_0_data
	wire          leds_s1_agent_rdata_fifo_src_ready;                                               // avalon_st_adapter:in_0_ready -> LEDs_s1_agent:rdata_fifo_src_ready
	wire          avalon_st_adapter_out_0_valid;                                                    // avalon_st_adapter:out_0_valid -> LEDs_s1_agent:rdata_fifo_sink_valid
	wire   [33:0] avalon_st_adapter_out_0_data;                                                     // avalon_st_adapter:out_0_data -> LEDs_s1_agent:rdata_fifo_sink_data
	wire          avalon_st_adapter_out_0_ready;                                                    // LEDs_s1_agent:rdata_fifo_sink_ready -> avalon_st_adapter:out_0_ready
	wire    [0:0] avalon_st_adapter_out_0_error;                                                    // avalon_st_adapter:out_0_error -> LEDs_s1_agent:rdata_fifo_sink_error
	wire          hex3_hex0_s1_agent_rdata_fifo_src_valid;                                          // HEX3_HEX0_s1_agent:rdata_fifo_src_valid -> avalon_st_adapter_001:in_0_valid
	wire   [33:0] hex3_hex0_s1_agent_rdata_fifo_src_data;                                           // HEX3_HEX0_s1_agent:rdata_fifo_src_data -> avalon_st_adapter_001:in_0_data
	wire          hex3_hex0_s1_agent_rdata_fifo_src_ready;                                          // avalon_st_adapter_001:in_0_ready -> HEX3_HEX0_s1_agent:rdata_fifo_src_ready
	wire          avalon_st_adapter_001_out_0_valid;                                                // avalon_st_adapter_001:out_0_valid -> HEX3_HEX0_s1_agent:rdata_fifo_sink_valid
	wire   [33:0] avalon_st_adapter_001_out_0_data;                                                 // avalon_st_adapter_001:out_0_data -> HEX3_HEX0_s1_agent:rdata_fifo_sink_data
	wire          avalon_st_adapter_001_out_0_ready;                                                // HEX3_HEX0_s1_agent:rdata_fifo_sink_ready -> avalon_st_adapter_001:out_0_ready
	wire    [0:0] avalon_st_adapter_001_out_0_error;                                                // avalon_st_adapter_001:out_0_error -> HEX3_HEX0_s1_agent:rdata_fifo_sink_error

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (30),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (30),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (0),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) external_master_avalon_master_translator (
		.clk                    (System_PLL_sys_clk_clk),                                                           //                       clk.clk
		.reset                  (External_master_reset_reset_bridge_in_reset_reset),                                //                     reset.reset
		.uav_address            (external_master_avalon_master_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (external_master_avalon_master_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (external_master_avalon_master_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (external_master_avalon_master_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (external_master_avalon_master_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (external_master_avalon_master_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (external_master_avalon_master_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (external_master_avalon_master_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (external_master_avalon_master_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (external_master_avalon_master_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (external_master_avalon_master_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (External_master_avalon_master_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (External_master_avalon_master_waitrequest),                                        //                          .waitrequest
		.av_byteenable          (External_master_avalon_master_byteenable),                                         //                          .byteenable
		.av_read                (External_master_avalon_master_read),                                               //                          .read
		.av_readdata            (External_master_avalon_master_readdata),                                           //                          .readdata
		.av_write               (External_master_avalon_master_write),                                              //                          .write
		.av_writedata           (External_master_avalon_master_writedata),                                          //                          .writedata
		.av_burstcount          (1'b1),                                                                             //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                             //               (terminated)
		.av_begintransfer       (1'b0),                                                                             //               (terminated)
		.av_chipselect          (1'b0),                                                                             //               (terminated)
		.av_readdatavalid       (),                                                                                 //               (terminated)
		.av_lock                (1'b0),                                                                             //               (terminated)
		.av_debugaccess         (1'b0),                                                                             //               (terminated)
		.uav_clken              (),                                                                                 //               (terminated)
		.av_clken               (1'b1),                                                                             //               (terminated)
		.uav_response           (2'b00),                                                                            //               (terminated)
		.av_response            (),                                                                                 //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                             //               (terminated)
		.av_writeresponsevalid  ()                                                                                  //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (2),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (1),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (30),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) leds_s1_translator (
		.clk                    (System_PLL_sys_clk_clk),                            //                      clk.clk
		.reset                  (External_master_reset_reset_bridge_in_reset_reset), //                    reset.reset
		.uav_address            (leds_s1_agent_m0_address),                          // avalon_universal_slave_0.address
		.uav_burstcount         (leds_s1_agent_m0_burstcount),                       //                         .burstcount
		.uav_read               (leds_s1_agent_m0_read),                             //                         .read
		.uav_write              (leds_s1_agent_m0_write),                            //                         .write
		.uav_waitrequest        (leds_s1_agent_m0_waitrequest),                      //                         .waitrequest
		.uav_readdatavalid      (leds_s1_agent_m0_readdatavalid),                    //                         .readdatavalid
		.uav_byteenable         (leds_s1_agent_m0_byteenable),                       //                         .byteenable
		.uav_readdata           (leds_s1_agent_m0_readdata),                         //                         .readdata
		.uav_writedata          (leds_s1_agent_m0_writedata),                        //                         .writedata
		.uav_lock               (leds_s1_agent_m0_lock),                             //                         .lock
		.uav_debugaccess        (leds_s1_agent_m0_debugaccess),                      //                         .debugaccess
		.av_address             (LEDs_s1_address),                                   //      avalon_anti_slave_0.address
		.av_write               (LEDs_s1_write),                                     //                         .write
		.av_readdata            (LEDs_s1_readdata),                                  //                         .readdata
		.av_writedata           (LEDs_s1_writedata),                                 //                         .writedata
		.av_chipselect          (LEDs_s1_chipselect),                                //                         .chipselect
		.av_read                (),                                                  //              (terminated)
		.av_begintransfer       (),                                                  //              (terminated)
		.av_beginbursttransfer  (),                                                  //              (terminated)
		.av_burstcount          (),                                                  //              (terminated)
		.av_byteenable          (),                                                  //              (terminated)
		.av_readdatavalid       (1'b0),                                              //              (terminated)
		.av_waitrequest         (1'b0),                                              //              (terminated)
		.av_writebyteenable     (),                                                  //              (terminated)
		.av_lock                (),                                                  //              (terminated)
		.av_clken               (),                                                  //              (terminated)
		.uav_clken              (1'b0),                                              //              (terminated)
		.av_debugaccess         (),                                                  //              (terminated)
		.av_outputenable        (),                                                  //              (terminated)
		.uav_response           (),                                                  //              (terminated)
		.av_response            (2'b00),                                             //              (terminated)
		.uav_writeresponsevalid (),                                                  //              (terminated)
		.av_writeresponsevalid  (1'b0)                                               //              (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (2),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (1),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (30),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) hex3_hex0_s1_translator (
		.clk                    (System_PLL_sys_clk_clk),                            //                      clk.clk
		.reset                  (External_master_reset_reset_bridge_in_reset_reset), //                    reset.reset
		.uav_address            (hex3_hex0_s1_agent_m0_address),                     // avalon_universal_slave_0.address
		.uav_burstcount         (hex3_hex0_s1_agent_m0_burstcount),                  //                         .burstcount
		.uav_read               (hex3_hex0_s1_agent_m0_read),                        //                         .read
		.uav_write              (hex3_hex0_s1_agent_m0_write),                       //                         .write
		.uav_waitrequest        (hex3_hex0_s1_agent_m0_waitrequest),                 //                         .waitrequest
		.uav_readdatavalid      (hex3_hex0_s1_agent_m0_readdatavalid),               //                         .readdatavalid
		.uav_byteenable         (hex3_hex0_s1_agent_m0_byteenable),                  //                         .byteenable
		.uav_readdata           (hex3_hex0_s1_agent_m0_readdata),                    //                         .readdata
		.uav_writedata          (hex3_hex0_s1_agent_m0_writedata),                   //                         .writedata
		.uav_lock               (hex3_hex0_s1_agent_m0_lock),                        //                         .lock
		.uav_debugaccess        (hex3_hex0_s1_agent_m0_debugaccess),                 //                         .debugaccess
		.av_address             (HEX3_HEX0_s1_address),                              //      avalon_anti_slave_0.address
		.av_write               (HEX3_HEX0_s1_write),                                //                         .write
		.av_readdata            (HEX3_HEX0_s1_readdata),                             //                         .readdata
		.av_writedata           (HEX3_HEX0_s1_writedata),                            //                         .writedata
		.av_chipselect          (HEX3_HEX0_s1_chipselect),                           //                         .chipselect
		.av_read                (),                                                  //              (terminated)
		.av_begintransfer       (),                                                  //              (terminated)
		.av_beginbursttransfer  (),                                                  //              (terminated)
		.av_burstcount          (),                                                  //              (terminated)
		.av_byteenable          (),                                                  //              (terminated)
		.av_readdatavalid       (1'b0),                                              //              (terminated)
		.av_waitrequest         (1'b0),                                              //              (terminated)
		.av_writebyteenable     (),                                                  //              (terminated)
		.av_lock                (),                                                  //              (terminated)
		.av_clken               (),                                                  //              (terminated)
		.uav_clken              (1'b0),                                              //              (terminated)
		.av_debugaccess         (),                                                  //              (terminated)
		.av_outputenable        (),                                                  //              (terminated)
		.uav_response           (),                                                  //              (terminated)
		.av_response            (2'b00),                                             //              (terminated)
		.uav_writeresponsevalid (),                                                  //              (terminated)
		.av_writeresponsevalid  (1'b0)                                               //              (terminated)
	);

	altera_merlin_master_agent #(
		.PKT_ORI_BURST_SIZE_H      (99),
		.PKT_ORI_BURST_SIZE_L      (97),
		.PKT_RESPONSE_STATUS_H     (96),
		.PKT_RESPONSE_STATUS_L     (95),
		.PKT_QOS_H                 (84),
		.PKT_QOS_L                 (84),
		.PKT_DATA_SIDEBAND_H       (82),
		.PKT_DATA_SIDEBAND_L       (82),
		.PKT_ADDR_SIDEBAND_H       (81),
		.PKT_ADDR_SIDEBAND_L       (81),
		.PKT_BURST_TYPE_H          (80),
		.PKT_BURST_TYPE_L          (79),
		.PKT_CACHE_H               (94),
		.PKT_CACHE_L               (91),
		.PKT_THREAD_ID_H           (87),
		.PKT_THREAD_ID_L           (87),
		.PKT_BURST_SIZE_H          (78),
		.PKT_BURST_SIZE_L          (76),
		.PKT_TRANS_EXCLUSIVE       (71),
		.PKT_TRANS_LOCK            (70),
		.PKT_BEGIN_BURST           (83),
		.PKT_PROTECTION_H          (90),
		.PKT_PROTECTION_L          (88),
		.PKT_BURSTWRAP_H           (75),
		.PKT_BURSTWRAP_L           (75),
		.PKT_BYTE_CNT_H            (74),
		.PKT_BYTE_CNT_L            (72),
		.PKT_ADDR_H                (65),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (66),
		.PKT_TRANS_POSTED          (67),
		.PKT_TRANS_WRITE           (68),
		.PKT_TRANS_READ            (69),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (85),
		.PKT_SRC_ID_L              (85),
		.PKT_DEST_ID_H             (86),
		.PKT_DEST_ID_L             (86),
		.ST_DATA_W                 (100),
		.ST_CHANNEL_W              (2),
		.AV_BURSTCOUNT_W           (3),
		.SUPPRESS_0_BYTEEN_RSP     (0),
		.ID                        (0),
		.BURSTWRAP_VALUE           (1),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0)
	) external_master_avalon_master_agent (
		.clk                   (System_PLL_sys_clk_clk),                                                           //       clk.clk
		.reset                 (External_master_reset_reset_bridge_in_reset_reset),                                // clk_reset.reset
		.av_address            (external_master_avalon_master_translator_avalon_universal_master_0_address),       //        av.address
		.av_write              (external_master_avalon_master_translator_avalon_universal_master_0_write),         //          .write
		.av_read               (external_master_avalon_master_translator_avalon_universal_master_0_read),          //          .read
		.av_writedata          (external_master_avalon_master_translator_avalon_universal_master_0_writedata),     //          .writedata
		.av_readdata           (external_master_avalon_master_translator_avalon_universal_master_0_readdata),      //          .readdata
		.av_waitrequest        (external_master_avalon_master_translator_avalon_universal_master_0_waitrequest),   //          .waitrequest
		.av_readdatavalid      (external_master_avalon_master_translator_avalon_universal_master_0_readdatavalid), //          .readdatavalid
		.av_byteenable         (external_master_avalon_master_translator_avalon_universal_master_0_byteenable),    //          .byteenable
		.av_burstcount         (external_master_avalon_master_translator_avalon_universal_master_0_burstcount),    //          .burstcount
		.av_debugaccess        (external_master_avalon_master_translator_avalon_universal_master_0_debugaccess),   //          .debugaccess
		.av_lock               (external_master_avalon_master_translator_avalon_universal_master_0_lock),          //          .lock
		.cp_valid              (external_master_avalon_master_agent_cp_valid),                                     //        cp.valid
		.cp_data               (external_master_avalon_master_agent_cp_data),                                      //          .data
		.cp_startofpacket      (external_master_avalon_master_agent_cp_startofpacket),                             //          .startofpacket
		.cp_endofpacket        (external_master_avalon_master_agent_cp_endofpacket),                               //          .endofpacket
		.cp_ready              (external_master_avalon_master_agent_cp_ready),                                     //          .ready
		.rp_valid              (rsp_mux_src_valid),                                                                //        rp.valid
		.rp_data               (rsp_mux_src_data),                                                                 //          .data
		.rp_channel            (rsp_mux_src_channel),                                                              //          .channel
		.rp_startofpacket      (rsp_mux_src_startofpacket),                                                        //          .startofpacket
		.rp_endofpacket        (rsp_mux_src_endofpacket),                                                          //          .endofpacket
		.rp_ready              (rsp_mux_src_ready),                                                                //          .ready
		.av_response           (),                                                                                 // (terminated)
		.av_writeresponsevalid ()                                                                                  // (terminated)
	);

	altera_merlin_slave_agent #(
		.PKT_ORI_BURST_SIZE_H      (99),
		.PKT_ORI_BURST_SIZE_L      (97),
		.PKT_RESPONSE_STATUS_H     (96),
		.PKT_RESPONSE_STATUS_L     (95),
		.PKT_BURST_SIZE_H          (78),
		.PKT_BURST_SIZE_L          (76),
		.PKT_TRANS_LOCK            (70),
		.PKT_BEGIN_BURST           (83),
		.PKT_PROTECTION_H          (90),
		.PKT_PROTECTION_L          (88),
		.PKT_BURSTWRAP_H           (75),
		.PKT_BURSTWRAP_L           (75),
		.PKT_BYTE_CNT_H            (74),
		.PKT_BYTE_CNT_L            (72),
		.PKT_ADDR_H                (65),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (66),
		.PKT_TRANS_POSTED          (67),
		.PKT_TRANS_WRITE           (68),
		.PKT_TRANS_READ            (69),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (85),
		.PKT_SRC_ID_L              (85),
		.PKT_DEST_ID_H             (86),
		.PKT_DEST_ID_L             (86),
		.PKT_SYMBOL_W              (8),
		.ST_CHANNEL_W              (2),
		.ST_DATA_W                 (100),
		.AVS_BURSTCOUNT_W          (3),
		.SUPPRESS_0_BYTEEN_CMD     (0),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.ECC_ENABLE                (0)
	) leds_s1_agent (
		.clk                     (System_PLL_sys_clk_clk),                            //             clk.clk
		.reset                   (External_master_reset_reset_bridge_in_reset_reset), //       clk_reset.reset
		.m0_address              (leds_s1_agent_m0_address),                          //              m0.address
		.m0_burstcount           (leds_s1_agent_m0_burstcount),                       //                .burstcount
		.m0_byteenable           (leds_s1_agent_m0_byteenable),                       //                .byteenable
		.m0_debugaccess          (leds_s1_agent_m0_debugaccess),                      //                .debugaccess
		.m0_lock                 (leds_s1_agent_m0_lock),                             //                .lock
		.m0_readdata             (leds_s1_agent_m0_readdata),                         //                .readdata
		.m0_readdatavalid        (leds_s1_agent_m0_readdatavalid),                    //                .readdatavalid
		.m0_read                 (leds_s1_agent_m0_read),                             //                .read
		.m0_waitrequest          (leds_s1_agent_m0_waitrequest),                      //                .waitrequest
		.m0_writedata            (leds_s1_agent_m0_writedata),                        //                .writedata
		.m0_write                (leds_s1_agent_m0_write),                            //                .write
		.rp_endofpacket          (leds_s1_agent_rp_endofpacket),                      //              rp.endofpacket
		.rp_ready                (leds_s1_agent_rp_ready),                            //                .ready
		.rp_valid                (leds_s1_agent_rp_valid),                            //                .valid
		.rp_data                 (leds_s1_agent_rp_data),                             //                .data
		.rp_startofpacket        (leds_s1_agent_rp_startofpacket),                    //                .startofpacket
		.cp_ready                (cmd_mux_src_ready),                                 //              cp.ready
		.cp_valid                (cmd_mux_src_valid),                                 //                .valid
		.cp_data                 (cmd_mux_src_data),                                  //                .data
		.cp_startofpacket        (cmd_mux_src_startofpacket),                         //                .startofpacket
		.cp_endofpacket          (cmd_mux_src_endofpacket),                           //                .endofpacket
		.cp_channel              (cmd_mux_src_channel),                               //                .channel
		.rf_sink_ready           (leds_s1_agent_rsp_fifo_out_ready),                  //         rf_sink.ready
		.rf_sink_valid           (leds_s1_agent_rsp_fifo_out_valid),                  //                .valid
		.rf_sink_startofpacket   (leds_s1_agent_rsp_fifo_out_startofpacket),          //                .startofpacket
		.rf_sink_endofpacket     (leds_s1_agent_rsp_fifo_out_endofpacket),            //                .endofpacket
		.rf_sink_data            (leds_s1_agent_rsp_fifo_out_data),                   //                .data
		.rf_source_ready         (leds_s1_agent_rf_source_ready),                     //       rf_source.ready
		.rf_source_valid         (leds_s1_agent_rf_source_valid),                     //                .valid
		.rf_source_startofpacket (leds_s1_agent_rf_source_startofpacket),             //                .startofpacket
		.rf_source_endofpacket   (leds_s1_agent_rf_source_endofpacket),               //                .endofpacket
		.rf_source_data          (leds_s1_agent_rf_source_data),                      //                .data
		.rdata_fifo_sink_ready   (avalon_st_adapter_out_0_ready),                     // rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (avalon_st_adapter_out_0_valid),                     //                .valid
		.rdata_fifo_sink_data    (avalon_st_adapter_out_0_data),                      //                .data
		.rdata_fifo_sink_error   (avalon_st_adapter_out_0_error),                     //                .error
		.rdata_fifo_src_ready    (leds_s1_agent_rdata_fifo_src_ready),                //  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (leds_s1_agent_rdata_fifo_src_valid),                //                .valid
		.rdata_fifo_src_data     (leds_s1_agent_rdata_fifo_src_data),                 //                .data
		.m0_response             (2'b00),                                             //     (terminated)
		.m0_writeresponsevalid   (1'b0)                                               //     (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (101),
		.FIFO_DEPTH          (2),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) leds_s1_agent_rsp_fifo (
		.clk               (System_PLL_sys_clk_clk),                            //       clk.clk
		.reset             (External_master_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_data           (leds_s1_agent_rf_source_data),                      //        in.data
		.in_valid          (leds_s1_agent_rf_source_valid),                     //          .valid
		.in_ready          (leds_s1_agent_rf_source_ready),                     //          .ready
		.in_startofpacket  (leds_s1_agent_rf_source_startofpacket),             //          .startofpacket
		.in_endofpacket    (leds_s1_agent_rf_source_endofpacket),               //          .endofpacket
		.out_data          (leds_s1_agent_rsp_fifo_out_data),                   //       out.data
		.out_valid         (leds_s1_agent_rsp_fifo_out_valid),                  //          .valid
		.out_ready         (leds_s1_agent_rsp_fifo_out_ready),                  //          .ready
		.out_startofpacket (leds_s1_agent_rsp_fifo_out_startofpacket),          //          .startofpacket
		.out_endofpacket   (leds_s1_agent_rsp_fifo_out_endofpacket),            //          .endofpacket
		.csr_address       (2'b00),                                             // (terminated)
		.csr_read          (1'b0),                                              // (terminated)
		.csr_write         (1'b0),                                              // (terminated)
		.csr_readdata      (),                                                  // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),              // (terminated)
		.almost_full_data  (),                                                  // (terminated)
		.almost_empty_data (),                                                  // (terminated)
		.in_empty          (1'b0),                                              // (terminated)
		.out_empty         (),                                                  // (terminated)
		.in_error          (1'b0),                                              // (terminated)
		.out_error         (),                                                  // (terminated)
		.in_channel        (1'b0),                                              // (terminated)
		.out_channel       ()                                                   // (terminated)
	);

	altera_merlin_slave_agent #(
		.PKT_ORI_BURST_SIZE_H      (99),
		.PKT_ORI_BURST_SIZE_L      (97),
		.PKT_RESPONSE_STATUS_H     (96),
		.PKT_RESPONSE_STATUS_L     (95),
		.PKT_BURST_SIZE_H          (78),
		.PKT_BURST_SIZE_L          (76),
		.PKT_TRANS_LOCK            (70),
		.PKT_BEGIN_BURST           (83),
		.PKT_PROTECTION_H          (90),
		.PKT_PROTECTION_L          (88),
		.PKT_BURSTWRAP_H           (75),
		.PKT_BURSTWRAP_L           (75),
		.PKT_BYTE_CNT_H            (74),
		.PKT_BYTE_CNT_L            (72),
		.PKT_ADDR_H                (65),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (66),
		.PKT_TRANS_POSTED          (67),
		.PKT_TRANS_WRITE           (68),
		.PKT_TRANS_READ            (69),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (85),
		.PKT_SRC_ID_L              (85),
		.PKT_DEST_ID_H             (86),
		.PKT_DEST_ID_L             (86),
		.PKT_SYMBOL_W              (8),
		.ST_CHANNEL_W              (2),
		.ST_DATA_W                 (100),
		.AVS_BURSTCOUNT_W          (3),
		.SUPPRESS_0_BYTEEN_CMD     (0),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.ECC_ENABLE                (0)
	) hex3_hex0_s1_agent (
		.clk                     (System_PLL_sys_clk_clk),                            //             clk.clk
		.reset                   (External_master_reset_reset_bridge_in_reset_reset), //       clk_reset.reset
		.m0_address              (hex3_hex0_s1_agent_m0_address),                     //              m0.address
		.m0_burstcount           (hex3_hex0_s1_agent_m0_burstcount),                  //                .burstcount
		.m0_byteenable           (hex3_hex0_s1_agent_m0_byteenable),                  //                .byteenable
		.m0_debugaccess          (hex3_hex0_s1_agent_m0_debugaccess),                 //                .debugaccess
		.m0_lock                 (hex3_hex0_s1_agent_m0_lock),                        //                .lock
		.m0_readdata             (hex3_hex0_s1_agent_m0_readdata),                    //                .readdata
		.m0_readdatavalid        (hex3_hex0_s1_agent_m0_readdatavalid),               //                .readdatavalid
		.m0_read                 (hex3_hex0_s1_agent_m0_read),                        //                .read
		.m0_waitrequest          (hex3_hex0_s1_agent_m0_waitrequest),                 //                .waitrequest
		.m0_writedata            (hex3_hex0_s1_agent_m0_writedata),                   //                .writedata
		.m0_write                (hex3_hex0_s1_agent_m0_write),                       //                .write
		.rp_endofpacket          (hex3_hex0_s1_agent_rp_endofpacket),                 //              rp.endofpacket
		.rp_ready                (hex3_hex0_s1_agent_rp_ready),                       //                .ready
		.rp_valid                (hex3_hex0_s1_agent_rp_valid),                       //                .valid
		.rp_data                 (hex3_hex0_s1_agent_rp_data),                        //                .data
		.rp_startofpacket        (hex3_hex0_s1_agent_rp_startofpacket),               //                .startofpacket
		.cp_ready                (cmd_mux_001_src_ready),                             //              cp.ready
		.cp_valid                (cmd_mux_001_src_valid),                             //                .valid
		.cp_data                 (cmd_mux_001_src_data),                              //                .data
		.cp_startofpacket        (cmd_mux_001_src_startofpacket),                     //                .startofpacket
		.cp_endofpacket          (cmd_mux_001_src_endofpacket),                       //                .endofpacket
		.cp_channel              (cmd_mux_001_src_channel),                           //                .channel
		.rf_sink_ready           (hex3_hex0_s1_agent_rsp_fifo_out_ready),             //         rf_sink.ready
		.rf_sink_valid           (hex3_hex0_s1_agent_rsp_fifo_out_valid),             //                .valid
		.rf_sink_startofpacket   (hex3_hex0_s1_agent_rsp_fifo_out_startofpacket),     //                .startofpacket
		.rf_sink_endofpacket     (hex3_hex0_s1_agent_rsp_fifo_out_endofpacket),       //                .endofpacket
		.rf_sink_data            (hex3_hex0_s1_agent_rsp_fifo_out_data),              //                .data
		.rf_source_ready         (hex3_hex0_s1_agent_rf_source_ready),                //       rf_source.ready
		.rf_source_valid         (hex3_hex0_s1_agent_rf_source_valid),                //                .valid
		.rf_source_startofpacket (hex3_hex0_s1_agent_rf_source_startofpacket),        //                .startofpacket
		.rf_source_endofpacket   (hex3_hex0_s1_agent_rf_source_endofpacket),          //                .endofpacket
		.rf_source_data          (hex3_hex0_s1_agent_rf_source_data),                 //                .data
		.rdata_fifo_sink_ready   (avalon_st_adapter_001_out_0_ready),                 // rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (avalon_st_adapter_001_out_0_valid),                 //                .valid
		.rdata_fifo_sink_data    (avalon_st_adapter_001_out_0_data),                  //                .data
		.rdata_fifo_sink_error   (avalon_st_adapter_001_out_0_error),                 //                .error
		.rdata_fifo_src_ready    (hex3_hex0_s1_agent_rdata_fifo_src_ready),           //  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (hex3_hex0_s1_agent_rdata_fifo_src_valid),           //                .valid
		.rdata_fifo_src_data     (hex3_hex0_s1_agent_rdata_fifo_src_data),            //                .data
		.m0_response             (2'b00),                                             //     (terminated)
		.m0_writeresponsevalid   (1'b0)                                               //     (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (101),
		.FIFO_DEPTH          (2),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) hex3_hex0_s1_agent_rsp_fifo (
		.clk               (System_PLL_sys_clk_clk),                            //       clk.clk
		.reset             (External_master_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_data           (hex3_hex0_s1_agent_rf_source_data),                 //        in.data
		.in_valid          (hex3_hex0_s1_agent_rf_source_valid),                //          .valid
		.in_ready          (hex3_hex0_s1_agent_rf_source_ready),                //          .ready
		.in_startofpacket  (hex3_hex0_s1_agent_rf_source_startofpacket),        //          .startofpacket
		.in_endofpacket    (hex3_hex0_s1_agent_rf_source_endofpacket),          //          .endofpacket
		.out_data          (hex3_hex0_s1_agent_rsp_fifo_out_data),              //       out.data
		.out_valid         (hex3_hex0_s1_agent_rsp_fifo_out_valid),             //          .valid
		.out_ready         (hex3_hex0_s1_agent_rsp_fifo_out_ready),             //          .ready
		.out_startofpacket (hex3_hex0_s1_agent_rsp_fifo_out_startofpacket),     //          .startofpacket
		.out_endofpacket   (hex3_hex0_s1_agent_rsp_fifo_out_endofpacket),       //          .endofpacket
		.csr_address       (2'b00),                                             // (terminated)
		.csr_read          (1'b0),                                              // (terminated)
		.csr_write         (1'b0),                                              // (terminated)
		.csr_readdata      (),                                                  // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),              // (terminated)
		.almost_full_data  (),                                                  // (terminated)
		.almost_empty_data (),                                                  // (terminated)
		.in_empty          (1'b0),                                              // (terminated)
		.out_empty         (),                                                  // (terminated)
		.in_error          (1'b0),                                              // (terminated)
		.out_error         (),                                                  // (terminated)
		.in_channel        (1'b0),                                              // (terminated)
		.out_channel       ()                                                   // (terminated)
	);

	Computer_System_mm_interconnect_0_router router (
		.sink_ready         (external_master_avalon_master_agent_cp_ready),         //      sink.ready
		.sink_valid         (external_master_avalon_master_agent_cp_valid),         //          .valid
		.sink_data          (external_master_avalon_master_agent_cp_data),          //          .data
		.sink_startofpacket (external_master_avalon_master_agent_cp_startofpacket), //          .startofpacket
		.sink_endofpacket   (external_master_avalon_master_agent_cp_endofpacket),   //          .endofpacket
		.clk                (System_PLL_sys_clk_clk),                               //       clk.clk
		.reset              (External_master_reset_reset_bridge_in_reset_reset),    // clk_reset.reset
		.src_ready          (router_src_ready),                                     //       src.ready
		.src_valid          (router_src_valid),                                     //          .valid
		.src_data           (router_src_data),                                      //          .data
		.src_channel        (router_src_channel),                                   //          .channel
		.src_startofpacket  (router_src_startofpacket),                             //          .startofpacket
		.src_endofpacket    (router_src_endofpacket)                                //          .endofpacket
	);

	Computer_System_mm_interconnect_0_router_001 router_001 (
		.sink_ready         (leds_s1_agent_rp_ready),                            //      sink.ready
		.sink_valid         (leds_s1_agent_rp_valid),                            //          .valid
		.sink_data          (leds_s1_agent_rp_data),                             //          .data
		.sink_startofpacket (leds_s1_agent_rp_startofpacket),                    //          .startofpacket
		.sink_endofpacket   (leds_s1_agent_rp_endofpacket),                      //          .endofpacket
		.clk                (System_PLL_sys_clk_clk),                            //       clk.clk
		.reset              (External_master_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_001_src_ready),                              //       src.ready
		.src_valid          (router_001_src_valid),                              //          .valid
		.src_data           (router_001_src_data),                               //          .data
		.src_channel        (router_001_src_channel),                            //          .channel
		.src_startofpacket  (router_001_src_startofpacket),                      //          .startofpacket
		.src_endofpacket    (router_001_src_endofpacket)                         //          .endofpacket
	);

	Computer_System_mm_interconnect_0_router_001 router_002 (
		.sink_ready         (hex3_hex0_s1_agent_rp_ready),                       //      sink.ready
		.sink_valid         (hex3_hex0_s1_agent_rp_valid),                       //          .valid
		.sink_data          (hex3_hex0_s1_agent_rp_data),                        //          .data
		.sink_startofpacket (hex3_hex0_s1_agent_rp_startofpacket),               //          .startofpacket
		.sink_endofpacket   (hex3_hex0_s1_agent_rp_endofpacket),                 //          .endofpacket
		.clk                (System_PLL_sys_clk_clk),                            //       clk.clk
		.reset              (External_master_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_002_src_ready),                              //       src.ready
		.src_valid          (router_002_src_valid),                              //          .valid
		.src_data           (router_002_src_data),                               //          .data
		.src_channel        (router_002_src_channel),                            //          .channel
		.src_startofpacket  (router_002_src_startofpacket),                      //          .startofpacket
		.src_endofpacket    (router_002_src_endofpacket)                         //          .endofpacket
	);

	Computer_System_mm_interconnect_0_cmd_demux cmd_demux (
		.clk                (System_PLL_sys_clk_clk),                            //       clk.clk
		.reset              (External_master_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_src_ready),                                  //      sink.ready
		.sink_channel       (router_src_channel),                                //          .channel
		.sink_data          (router_src_data),                                   //          .data
		.sink_startofpacket (router_src_startofpacket),                          //          .startofpacket
		.sink_endofpacket   (router_src_endofpacket),                            //          .endofpacket
		.sink_valid         (router_src_valid),                                  //          .valid
		.src0_ready         (cmd_demux_src0_ready),                              //      src0.ready
		.src0_valid         (cmd_demux_src0_valid),                              //          .valid
		.src0_data          (cmd_demux_src0_data),                               //          .data
		.src0_channel       (cmd_demux_src0_channel),                            //          .channel
		.src0_startofpacket (cmd_demux_src0_startofpacket),                      //          .startofpacket
		.src0_endofpacket   (cmd_demux_src0_endofpacket),                        //          .endofpacket
		.src1_ready         (cmd_demux_src1_ready),                              //      src1.ready
		.src1_valid         (cmd_demux_src1_valid),                              //          .valid
		.src1_data          (cmd_demux_src1_data),                               //          .data
		.src1_channel       (cmd_demux_src1_channel),                            //          .channel
		.src1_startofpacket (cmd_demux_src1_startofpacket),                      //          .startofpacket
		.src1_endofpacket   (cmd_demux_src1_endofpacket)                         //          .endofpacket
	);

	Computer_System_mm_interconnect_0_cmd_mux cmd_mux (
		.clk                 (System_PLL_sys_clk_clk),                            //       clk.clk
		.reset               (External_master_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (cmd_mux_src_ready),                                 //       src.ready
		.src_valid           (cmd_mux_src_valid),                                 //          .valid
		.src_data            (cmd_mux_src_data),                                  //          .data
		.src_channel         (cmd_mux_src_channel),                               //          .channel
		.src_startofpacket   (cmd_mux_src_startofpacket),                         //          .startofpacket
		.src_endofpacket     (cmd_mux_src_endofpacket),                           //          .endofpacket
		.sink0_ready         (cmd_demux_src0_ready),                              //     sink0.ready
		.sink0_valid         (cmd_demux_src0_valid),                              //          .valid
		.sink0_channel       (cmd_demux_src0_channel),                            //          .channel
		.sink0_data          (cmd_demux_src0_data),                               //          .data
		.sink0_startofpacket (cmd_demux_src0_startofpacket),                      //          .startofpacket
		.sink0_endofpacket   (cmd_demux_src0_endofpacket)                         //          .endofpacket
	);

	Computer_System_mm_interconnect_0_cmd_mux cmd_mux_001 (
		.clk                 (System_PLL_sys_clk_clk),                            //       clk.clk
		.reset               (External_master_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (cmd_mux_001_src_ready),                             //       src.ready
		.src_valid           (cmd_mux_001_src_valid),                             //          .valid
		.src_data            (cmd_mux_001_src_data),                              //          .data
		.src_channel         (cmd_mux_001_src_channel),                           //          .channel
		.src_startofpacket   (cmd_mux_001_src_startofpacket),                     //          .startofpacket
		.src_endofpacket     (cmd_mux_001_src_endofpacket),                       //          .endofpacket
		.sink0_ready         (cmd_demux_src1_ready),                              //     sink0.ready
		.sink0_valid         (cmd_demux_src1_valid),                              //          .valid
		.sink0_channel       (cmd_demux_src1_channel),                            //          .channel
		.sink0_data          (cmd_demux_src1_data),                               //          .data
		.sink0_startofpacket (cmd_demux_src1_startofpacket),                      //          .startofpacket
		.sink0_endofpacket   (cmd_demux_src1_endofpacket)                         //          .endofpacket
	);

	Computer_System_mm_interconnect_0_rsp_demux rsp_demux (
		.clk                (System_PLL_sys_clk_clk),                            //       clk.clk
		.reset              (External_master_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_001_src_ready),                              //      sink.ready
		.sink_channel       (router_001_src_channel),                            //          .channel
		.sink_data          (router_001_src_data),                               //          .data
		.sink_startofpacket (router_001_src_startofpacket),                      //          .startofpacket
		.sink_endofpacket   (router_001_src_endofpacket),                        //          .endofpacket
		.sink_valid         (router_001_src_valid),                              //          .valid
		.src0_ready         (rsp_demux_src0_ready),                              //      src0.ready
		.src0_valid         (rsp_demux_src0_valid),                              //          .valid
		.src0_data          (rsp_demux_src0_data),                               //          .data
		.src0_channel       (rsp_demux_src0_channel),                            //          .channel
		.src0_startofpacket (rsp_demux_src0_startofpacket),                      //          .startofpacket
		.src0_endofpacket   (rsp_demux_src0_endofpacket)                         //          .endofpacket
	);

	Computer_System_mm_interconnect_0_rsp_demux rsp_demux_001 (
		.clk                (System_PLL_sys_clk_clk),                            //       clk.clk
		.reset              (External_master_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_002_src_ready),                              //      sink.ready
		.sink_channel       (router_002_src_channel),                            //          .channel
		.sink_data          (router_002_src_data),                               //          .data
		.sink_startofpacket (router_002_src_startofpacket),                      //          .startofpacket
		.sink_endofpacket   (router_002_src_endofpacket),                        //          .endofpacket
		.sink_valid         (router_002_src_valid),                              //          .valid
		.src0_ready         (rsp_demux_001_src0_ready),                          //      src0.ready
		.src0_valid         (rsp_demux_001_src0_valid),                          //          .valid
		.src0_data          (rsp_demux_001_src0_data),                           //          .data
		.src0_channel       (rsp_demux_001_src0_channel),                        //          .channel
		.src0_startofpacket (rsp_demux_001_src0_startofpacket),                  //          .startofpacket
		.src0_endofpacket   (rsp_demux_001_src0_endofpacket)                     //          .endofpacket
	);

	Computer_System_mm_interconnect_0_rsp_mux rsp_mux (
		.clk                 (System_PLL_sys_clk_clk),                            //       clk.clk
		.reset               (External_master_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_mux_src_ready),                                 //       src.ready
		.src_valid           (rsp_mux_src_valid),                                 //          .valid
		.src_data            (rsp_mux_src_data),                                  //          .data
		.src_channel         (rsp_mux_src_channel),                               //          .channel
		.src_startofpacket   (rsp_mux_src_startofpacket),                         //          .startofpacket
		.src_endofpacket     (rsp_mux_src_endofpacket),                           //          .endofpacket
		.sink0_ready         (rsp_demux_src0_ready),                              //     sink0.ready
		.sink0_valid         (rsp_demux_src0_valid),                              //          .valid
		.sink0_channel       (rsp_demux_src0_channel),                            //          .channel
		.sink0_data          (rsp_demux_src0_data),                               //          .data
		.sink0_startofpacket (rsp_demux_src0_startofpacket),                      //          .startofpacket
		.sink0_endofpacket   (rsp_demux_src0_endofpacket),                        //          .endofpacket
		.sink1_ready         (rsp_demux_001_src0_ready),                          //     sink1.ready
		.sink1_valid         (rsp_demux_001_src0_valid),                          //          .valid
		.sink1_channel       (rsp_demux_001_src0_channel),                        //          .channel
		.sink1_data          (rsp_demux_001_src0_data),                           //          .data
		.sink1_startofpacket (rsp_demux_001_src0_startofpacket),                  //          .startofpacket
		.sink1_endofpacket   (rsp_demux_001_src0_endofpacket)                     //          .endofpacket
	);

	Computer_System_mm_interconnect_0_avalon_st_adapter #(
		.inBitsPerSymbol (34),
		.inUsePackets    (0),
		.inDataWidth     (34),
		.inChannelWidth  (0),
		.inErrorWidth    (0),
		.inUseEmptyPort  (0),
		.inUseValid      (1),
		.inUseReady      (1),
		.inReadyLatency  (0),
		.outDataWidth    (34),
		.outChannelWidth (0),
		.outErrorWidth   (1),
		.outUseEmptyPort (0),
		.outUseValid     (1),
		.outUseReady     (1),
		.outReadyLatency (0)
	) avalon_st_adapter (
		.in_clk_0_clk   (System_PLL_sys_clk_clk),                            // in_clk_0.clk
		.in_rst_0_reset (External_master_reset_reset_bridge_in_reset_reset), // in_rst_0.reset
		.in_0_data      (leds_s1_agent_rdata_fifo_src_data),                 //     in_0.data
		.in_0_valid     (leds_s1_agent_rdata_fifo_src_valid),                //         .valid
		.in_0_ready     (leds_s1_agent_rdata_fifo_src_ready),                //         .ready
		.out_0_data     (avalon_st_adapter_out_0_data),                      //    out_0.data
		.out_0_valid    (avalon_st_adapter_out_0_valid),                     //         .valid
		.out_0_ready    (avalon_st_adapter_out_0_ready),                     //         .ready
		.out_0_error    (avalon_st_adapter_out_0_error)                      //         .error
	);

	Computer_System_mm_interconnect_0_avalon_st_adapter #(
		.inBitsPerSymbol (34),
		.inUsePackets    (0),
		.inDataWidth     (34),
		.inChannelWidth  (0),
		.inErrorWidth    (0),
		.inUseEmptyPort  (0),
		.inUseValid      (1),
		.inUseReady      (1),
		.inReadyLatency  (0),
		.outDataWidth    (34),
		.outChannelWidth (0),
		.outErrorWidth   (1),
		.outUseEmptyPort (0),
		.outUseValid     (1),
		.outUseReady     (1),
		.outReadyLatency (0)
	) avalon_st_adapter_001 (
		.in_clk_0_clk   (System_PLL_sys_clk_clk),                            // in_clk_0.clk
		.in_rst_0_reset (External_master_reset_reset_bridge_in_reset_reset), // in_rst_0.reset
		.in_0_data      (hex3_hex0_s1_agent_rdata_fifo_src_data),            //     in_0.data
		.in_0_valid     (hex3_hex0_s1_agent_rdata_fifo_src_valid),           //         .valid
		.in_0_ready     (hex3_hex0_s1_agent_rdata_fifo_src_ready),           //         .ready
		.out_0_data     (avalon_st_adapter_001_out_0_data),                  //    out_0.data
		.out_0_valid    (avalon_st_adapter_001_out_0_valid),                 //         .valid
		.out_0_ready    (avalon_st_adapter_001_out_0_ready),                 //         .ready
		.out_0_error    (avalon_st_adapter_001_out_0_error)                  //         .error
	);

endmodule
