
fsm:
	plantuml -v -keepfiles -tsvg ./ecpri_fsm_0.txt 
	plantuml -v -keepfiles -tsvg ./ecpri_fsm_1.txt 

block:
	dot -v -Tsvg ./ecpri_block_0.txt  -o ecpri_block_0.svg
	dot -v -Tsvg ./ecpri_block_1.txt  -o ecpri_block_1.svg
	dot -v -Tsvg ./ecpri_block_2.txt  -o ecpri_block_2.svg

