
fsm:
	#plantuml -v -keepfiles -tsvg ./ecpri_fsm_0.txt 
	#plantuml -v -keepfiles -tsvg ./ecpri_fsm_1.txt 
	plantuml -v -keepfiles -tsvg ./ecpri_fsm_2.txt 
	plantuml -v -keepfiles -tpng ./ecpri_fsm_2.txt 

block:
	dot -Tsvg ./ecpri_block_5.txt  -o ecpri_block_5.svg
	dot -Tpng ./ecpri_block_5.txt  -o ecpri_block_5.png

